### ISSUE TITLE
It's a great ext!! How to make it works in v1.5?

### ISSUE THREAD

**Issue by gozhhu** [DavidNery/flarum-nickname-group-formatter#2]
A crash is occured after enable.

`
Next Flarum\Extension\Exception\ExtensionBootError: Experienced an error while booting extension: Nickname Group Formatter.

Error occurred while applying an extender of type: Closure. in /data/php-src/blog-mydemo/vendor/flarum/core/src/Extension/Extension.php:143
Stack trace:
#0 /data/php-src/blog-mydemo/vendor/flarum/core/src/Extension/ExtensionManager.php(382): Flarum\Extension\Extension->extend()
#1 /data/php-src/blog-mydemo/vendor/flarum/core/src/Extension/ExtensionServiceProvider.php(31): Flarum\Extension\ExtensionManager->extend()
#2 [internal function]: Flarum\Extension\ExtensionServiceProvider->Flarum\Extension\{closure}()
#3 /data/php-src/blog-mydemo/vendor/flarum/core/src/Foundation/Application.php(329): call_user_func()
#4 /data/php-src/blog-mydemo/vendor/flarum/core/src/Foundation/Application.php(270): Flarum\Foundation\Application->fireAppCallbacks()
#5 /data/php-src/blog-mydemo/vendor/flarum/core/src/Foundation/InstalledSite.php(151): Flarum\Foundation\Application->boot()
#6 /data/php-src/blog-mydemo/vendor/flarum/core/src/Foundation/InstalledSite.php(82): Flarum\Foundation\InstalledSite->bootLaravel()
#7 /data/php-src/blog-mydemo/vendor/flarum/core/src/Http/Server.php(58): Flarum\Foundation\InstalledSite->bootApp()
#8 /data/php-src/blog-mydemo/vendor/flarum/core/src/Http/Server.php(35): Flarum\Http\Server->safelyBootAndGetHandler()
#9 /data/php-src/blog-mydemo/public/index.php(26): Flarum\Http\Server->listen()
#10 {main}  
[2022-11-05 10:54:50] flarum.ERROR: Error: Call to undefined method Closure::extend() in /data/php-src/blog-mydemo/vendor/flarum/core/src/Extension/Extension.php:141
Stack trace:
#0 /data/php-src/blog-mydemo/vendor/flarum/core/src/Extension/ExtensionManager.php(382): Flarum\Extension\Extension->extend()
#1 /data/php-src/blog-mydemo/vendor/flarum/core/src/Extension/ExtensionServiceProvider.php(31): Flarum\Extension\ExtensionManager->extend()
#2 [internal function]: Flarum\Extension\ExtensionServiceProvider->Flarum\Extension\{closure}()
#3 /data/php-src/blog-mydemo/vendor/flarum/core/src/Foundation/Application.php(329): call_user_func()
#4 /data/php-src/blog-mydemo/vendor/flarum/core/src/Foundation/Application.php(270): Flarum\Foundation\Application->fireAppCallbacks()
#5 /data/php-src/blog-mydemo/vendor/flarum/core/src/Foundation/InstalledSite.php(151): Flarum\Foundation\Application->boot()
#6 /data/php-src/blog-mydemo/vendor/flarum/core/src/Foundation/InstalledSite.php(82): Flarum\Foundation\InstalledSite->bootLaravel()
#7 /data/php-src/blog-mydemo/vendor/flarum/core/src/Http/Server.php(58): Flarum\Foundation\InstalledSite->bootApp()
#8 /data/php-src/blog-mydemo/vendor/flarum/core/src/Http/Server.php(35): Flarum\Http\Server->safelyBootAndGetHandler()
#9 /data/php-src/blog-mydemo/public/index.php(26): Flarum\Http\Server->listen()
#10 {main}

Next Flarum\Extension\Exception\ExtensionBootError: Experienced an error while booting extension: Nickname Group Formatter.

Error occurred while applying an extender of type: Closure. in /data/php-src/blog-mydemo/vendor/flarum/core/src/Extension/Extension.php:143
Stack trace:
#0 /data/php-src/blog-mydemo/vendor/flarum/core/src/Extension/ExtensionManager.php(382): Flarum\Extension\Extension->extend()
#1 /data/php-src/blog-mydemo/vendor/flarum/core/src/Extension/ExtensionServiceProvider.php(31): Flarum\Extension\ExtensionManager->extend()
#2 [internal function]: Flarum\Extension\ExtensionServiceProvider->Flarum\Extension\{closure}()
#3 /data/php-src/blog-mydemo/vendor/flarum/core/src/Foundation/Application.php(329): call_user_func()
#4 /data/php-src/blog-mydemo/vendor/flarum/core/src/Foundation/Application.php(270): Flarum\Foundation\Application->fireAppCallbacks()
#5 /data/php-src/blog-mydemo/vendor/flarum/core/src/Foundation/InstalledSite.php(151): Flarum\Foundation\Application->boot()
#6 /data/php-src/blog-mydemo/vendor/flarum/core/src/Foundation/InstalledSite.php(82): Flarum\Foundation\InstalledSite->bootLaravel()
#7 /data/php-src/blog-mydemo/vendor/flarum/core/src/Http/Server.php(58): Flarum\Foundation\InstalledSite->bootApp()
#8 /data/php-src/blog-mydemo/vendor/flarum/core/src/Http/Server.php(35): Flarum\Http\Server->safelyBootAndGetHandler()
#9 /data/php-src/blog-mydemo/public/index.php(26): Flarum\Http\Server->listen()
#10 {main}  `

**Comment by DavidNery** [comment]
I'll take a look soon. Thanks for the report!
